version: "3.8"

volumes:
  pgadmin_data_ballet:
  pg_data_ballet:
  pg_data_test:

services:
  db:
    container_name: ballet_db_container
    image: postgres:13
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data_ballet:/var/lib/postgresql/data

  db_test:
    container_name: ballet_db_test_container
    image: postgres:13
    env_file: .test.env
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - pg_data_test:/var/lib/postgresql/data

  pgadmin:
    container_name: ballet_pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ballet@ballet.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data_ballet:/var/lib/pgadmin

  bot:
    build: .
    command: sh -c "make migrate && python -m bot"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
