"""Create DataBase

Revision ID: b6b18360c34a
Revises: 
Create Date: 2024-02-26 20:20:08.667732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b18360c34a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    op.create_table('studios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_studios')),
    sa.UniqueConstraint('name', name=op.f('uq_studios_name'))
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], name=op.f('fk_groups_studio_id_studios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_table('individual_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('start_date', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='weekdays'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], name=op.f('fk_individual_lessons_studio_id_studios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_individual_lessons'))
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('start_date', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='weekdays'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_schedules_group_id_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_table('student_group_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_student_group_association_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_group_association_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_group_association')),
    sa.UniqueConstraint('group_id', 'student_id', name=op.f('uq_student_group_association_group_id'))
    )
    op.create_table('student_indiv_lesson_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_lesson_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['individual_lesson_id'], ['individual_lessons.id'], name=op.f('fk_student_indiv_lesson_association_individual_lesson_id_individual_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_indiv_lesson_association_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_indiv_lesson_association')),
    sa.UniqueConstraint('individual_lesson_id', 'student_id', name=op.f('uq_student_indiv_lesson_association_individual_lesson_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_indiv_lesson_association')
    op.drop_table('student_group_association')
    op.drop_table('schedules')
    op.drop_table('individual_lessons')
    op.drop_table('groups')
    op.drop_table('studios')
    op.drop_table('students')
    # ### end Alembic commands ###
