"""create database

Revision ID: 861191b480ea
Revises: 7242af2eb5e0
Create Date: 2024-02-26 19:29:21.643827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861191b480ea'
down_revision: Union[str, None] = '7242af2eb5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual_lessons', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('individual_lessons', 'notes')
    # ### end Alembic commands ###
